Repository afj-solution/buy-it-api, pull requests merged in 2022-08, with the labels that each got.

#11 Create user Request
  src/main/java/com/afj/solution/buyitapp/config/SecurityConfig.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/UserController.java
  src/main/java/com/afj/solution/buyitapp/model/User.java
  src/main/java/com/afj/solution/buyitapp/payload/request/CreateUserRequest.java
  src/main/java/com/afj/solution/buyitapp/service/UserAuthServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/UserService.java
  src/main/java/com/afj/solution/buyitapp/service/UserServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/converters/CreateUserRequestToUser.java
Labels: feature

#13 [API] Add get my orders API
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/AuthController.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/OrderController.java
  src/main/java/com/afj/solution/buyitapp/repository/OrderRepository.java
  src/main/java/com/afj/solution/buyitapp/service/order/OrderService.java
  src/main/java/com/afj/solution/buyitapp/service/order/OrderServiceImpl.java
Labels: feature

#14 [API] Cancel order
  .circleci/config.yml
  Dockerfile
  pom.xml
  src/main/java/com/afj/solution/buyitapp/common/Adapters.java
  src/main/java/com/afj/solution/buyitapp/config/WebMvcConfig.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/OrderController.java
  src/main/java/com/afj/solution/buyitapp/exception/EntityAlreadyExistsException.java
  src/main/java/com/afj/solution/buyitapp/exception/EntityNotFoundException.java
  src/main/java/com/afj/solution/buyitapp/model/enums/OrderStatus.java
  src/main/java/com/afj/solution/buyitapp/security/JwtTokenProvider.java
  src/main/java/com/afj/solution/buyitapp/service/UserAuthServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/order/OrderService.java
  src/main/java/com/afj/solution/buyitapp/service/order/OrderServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/product/ProductServiceImp.java
  src/main/resources/banner.txt
Labels: feature

#17 [DOC] Update the Readme.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/new_feature.md
  README.md
Labels: documentation

#18 [API] Fix the issue with the JWT token
  src/main/java/com/afj/solution/buyitapp/security/JwtTokenProvider.java
Labels: fix

#19 [CONFIG] Update the security config
  src/main/java/com/afj/solution/buyitapp/config/SecurityConfig.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/AuthController.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/LoginController.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/OrderController.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/ProductController.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/UserController.java
Labels: fix

#20 [API] Add create by user to the product model
  pom.xml
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/ProductController.java
  src/main/java/com/afj/solution/buyitapp/model/Product.java
  src/main/java/com/afj/solution/buyitapp/model/User.java
  src/main/java/com/afj/solution/buyitapp/model/UserLogin.java
  src/main/java/com/afj/solution/buyitapp/payload/response/CreatedByResponse.java
  src/main/java/com/afj/solution/buyitapp/payload/response/ProductResponse.java
  src/main/java/com/afj/solution/buyitapp/service/UserService.java
  src/main/java/com/afj/solution/buyitapp/service/UserServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/converters/order/OrderToResponseConverter.java
  src/main/java/com/afj/solution/buyitapp/service/converters/product/ProductRequestToProductConverter.java
  src/main/java/com/afj/solution/buyitapp/service/converters/product/ProductToResponseConverter.java
  src/main/java/com/afj/solution/buyitapp/service/converters/product/UpdateCharacteristicRequestToCharacteristicConverter.java
  src/main/java/com/afj/solution/buyitapp/service/converters/user/CreateUserRequestToUser.java
  src/main/java/com/afj/solution/buyitapp/service/converters/user/UserToResponseConverter.java
  src/main/java/com/afj/solution/buyitapp/service/order/OrderServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/product/ProductService.java
  src/main/java/com/afj/solution/buyitapp/service/product/ProductServiceImp.java
  src/main/resources/db/migration/V1.8__add_product_user_id.sql
Labels: feature

#26 [DevOPS] CORS policy fix
  src/main/java/com/afj/solution/buyitapp/config/WebMvcConfig.java
Labels: feature

#29 [FIX] Can not create a user with DOB
  src/main/java/com/afj/solution/buyitapp/common/Adapters.java
  src/main/java/com/afj/solution/buyitapp/model/User.java
  src/main/java/com/afj/solution/buyitapp/payload/request/CreateUserRequest.java
Labels: fix

#30 [API] Get my products
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/ProductController.java
  src/main/java/com/afj/solution/buyitapp/repository/ProductRepository.java
  src/main/java/com/afj/solution/buyitapp/repository/UserRepository.java
  src/main/java/com/afj/solution/buyitapp/service/UserServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/product/ProductService.java
  src/main/java/com/afj/solution/buyitapp/service/product/ProductServiceImp.java
Labels: feature, fix

#28 [API] Localization support
  src/main/java/com/afj/solution/buyitapp/DatabaseLoader.java
  src/main/java/com/afj/solution/buyitapp/common/Error.java
  src/main/java/com/afj/solution/buyitapp/common/Response.java
  src/main/java/com/afj/solution/buyitapp/config/SecurityConfig.java
  src/main/java/com/afj/solution/buyitapp/config/WebMvcConfig.java
  src/main/java/com/afj/solution/buyitapp/constans/Patterns.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/AuthController.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/LocalizeController.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/LoginController.java
  src/main/java/com/afj/solution/buyitapp/controller/api/v1/UserController.java
  src/main/java/com/afj/solution/buyitapp/exception/BadRequestException.java
  src/main/java/com/afj/solution/buyitapp/exception/CustomAuthenticationException.java
  src/main/java/com/afj/solution/buyitapp/exception/EntityAlreadyExistsException.java
  src/main/java/com/afj/solution/buyitapp/exception/EntityNotFoundException.java
  src/main/java/com/afj/solution/buyitapp/exception/ErrorControllerAdvice.java
  src/main/java/com/afj/solution/buyitapp/payload/request/CreateOrderRequest.java
  src/main/java/com/afj/solution/buyitapp/payload/request/CreateProductRequest.java
  src/main/java/com/afj/solution/buyitapp/payload/request/CreateUserRequest.java
  src/main/java/com/afj/solution/buyitapp/payload/request/LoginRequest.java
  src/main/java/com/afj/solution/buyitapp/payload/request/UpdateCharacteristicRequest.java
  src/main/java/com/afj/solution/buyitapp/payload/response/CharacteristicResponse.java
  src/main/java/com/afj/solution/buyitapp/payload/response/CreatedByResponse.java
  src/main/java/com/afj/solution/buyitapp/payload/response/ImageResponse.java
  src/main/java/com/afj/solution/buyitapp/payload/response/JwtResponse.java
  src/main/java/com/afj/solution/buyitapp/payload/response/OrderResponse.java
  src/main/java/com/afj/solution/buyitapp/payload/response/ProductResponse.java
  src/main/java/com/afj/solution/buyitapp/payload/response/UserResponse.java
  src/main/java/com/afj/solution/buyitapp/service/AppUserDetailsService.java
  src/main/java/com/afj/solution/buyitapp/service/localize/TranslatorService.java
  src/main/java/com/afj/solution/buyitapp/service/order/OrderServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/product/ProductServiceImp.java
  src/main/java/com/afj/solution/buyitapp/service/user/UserAuthService.java
  src/main/java/com/afj/solution/buyitapp/service/user/UserAuthServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/user/UserLoginService.java
  src/main/java/com/afj/solution/buyitapp/service/user/UserLoginServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/user/UserService.java
  src/main/java/com/afj/solution/buyitapp/service/user/UserServiceImpl.java
  src/main/resources/error.properties
  src/main/resources/error_hu.properties
  src/main/resources/error_ua.properties
  src/main/resources/forms.properties
  src/main/resources/forms_hu.properties
  src/main/resources/forms_ua.properties
Labels: feature

#33 [DevOPS] API cors policy with spring profiles
  .circleci/config.yml
  Dockerfile
  src/main/java/com/afj/solution/buyitapp/config/nonprod/SecurityDevConfig.java
  src/main/java/com/afj/solution/buyitapp/config/nonprod/WebMvcDevConfig.java
  src/main/java/com/afj/solution/buyitapp/config/nonprod/WebMvcLocalConfig.java
  src/main/java/com/afj/solution/buyitapp/config/prod/SecurityConfig.java
  src/main/java/com/afj/solution/buyitapp/config/prod/WebMvcConfig.java
  tools/notify.sh
Labels: feature

#34 [INFRA] Add more texts to localisation
  src/main/java/com/afj/solution/buyitapp/service/localize/TranslatorService.java
  src/main/resources/forms.properties
  src/main/resources/forms_hu.properties
  src/main/resources/forms_ua.properties
  src/main/resources/localize.properties
  src/main/resources/localize_hu.properties
  src/main/resources/localize_ua.properties
Labels: feature

#37 [INFRA] Fix the CORS policy issue
  src/main/java/com/afj/solution/buyitapp/config/nonprod/WebMvcDevConfig.java
Labels: fix

#38 [INFRA] Dev configuration cors policy error
  src/main/java/com/afj/solution/buyitapp/config/nonprod/WebMvcDevConfig.java
Labels: fix

#39 [UNIT] Setup unit tests
  .circleci/config.yml
  .gitignore
  flywayTestMigration.conf
  pom.xml
  sql/01.sql
  sql/prepare-db-for-tests.sql
  src/main/java/com/afj/solution/buyitapp/model/Order.java
  src/main/java/com/afj/solution/buyitapp/model/User.java
  src/main/java/com/afj/solution/buyitapp/service/order/OrderService.java
  src/main/java/com/afj/solution/buyitapp/service/order/OrderServiceImpl.java
  src/main/java/com/afj/solution/buyitapp/service/user/UserService.java
  src/main/java/com/afj/solution/buyitapp/service/user/UserServiceImpl.java
  src/main/resources/application-local.properties
  src/main/resources/db/migration/V1.9__change_product_id_table.sql
  src/test/java/com/afj/solution/buyitapp/service/BaseTest.java
  src/test/java/com/afj/solution/buyitapp/service/order/OrderServiceTest.java
Labels: tests

#40 [INFRA] Skip tests during build
  .circleci/config.yml
Labels: feature
